homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://localhost:1883
  user: '!secret user'
  password: '!secret password'
  keepalive: 60
  reject_unauthorized: true
  version: 4
serial:
  port: /dev/ttyUSB0
frontend:
  port: 8090
  auth_token: defender
  host: 0.0.0.0
availability: true
advanced:
  last_seen: ISO_8601_local
  network_key:
  legacy_api: false
  homeassistant_discovery_topic: homeassistant
  homeassistant_status_topic: homeassistant/status
  homeassistant_legacy_entity_attributes: false
  homeassistant_legacy_triggers: true
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 123
    protocol: tcp4
    type: '5424'
device_options:
  legacy: false
